### ISSUE TITLE
Docerina not generating docs when `.bal` files are in packages

### ISSUE THREAD

**Issue by moizalicious** [ballerinalang/docerina#142]
*Using 'ballerina-tools-0.95.5'*

I have the following function in the file `Concat.bal`,
```ballerina
@Description {value:"Concat two strings together"}
@Param {value:"s1: The first string"}
@Param {value:"s2: The second string"}
@Return {value:"string: The concatenated string"}
function concat (string s1, string s2) (string) {
    return s1 + s2;
}
```

When the file is not inside a package I can generate the documentation,
![image](https://user-images.githubusercontent.com/25219255/34240941-d52ee8ac-e637-11e7-96f9-936d01b01397.png)

But when I add the file inside a package called `stringUtils` I cannot seem to generate the docs in string utils,
![image](https://user-images.githubusercontent.com/25219255/34240991-2ceea15e-e638-11e7-8dfb-35c02b361f51.png)

Nor can I generate it through the name of the package itself.
![image](https://user-images.githubusercontent.com/25219255/34241160-895120ec-e639-11e7-8771-eeaf10cd44a1.png)

**Comment by hemikak** [comment]
Hi @moizalicious ,

To generate docs for packages, you need to give the path to the parent folder of the packages.

Say we have the following folder structure.
![screen shot 2018-01-23 at 4 31 28 pm](https://user-images.githubusercontent.com/4398820/35272326-e64b7c76-005a-11e8-83b1-72e3c52f65af.png)

You can invoke as following: 
`ballerina doc /tmp/packages/`
Or else you can go into the packages folder and invoke as follows: 
`ballerina doc .`

Reopen if issue exists.

**Comment by moizalicious** [comment]
Hi @hemikak ,

I tried to replicate the above in the latest version of Ballerina. Everything seems to be working fine now.

Thank You.
