### ISSUE TITLE
Cannot generate docs for source .bal files

### ISSUE THREAD

**Issue by lasinducharith** [ballerinalang/docerina#143]
Issue 1
=======
$ ballerina doc services/
docerina: API documentation generation for sources - [services/]
ballerina: source package/file cannot be null

Issue 2
======
$ballerina doc Main.bal 
docerina: API documentation generation for sources - [Main.bal]

The docs are not being generated. Im using the latest builds from master as of today.

**Comment by NatashaWso2** [comment]
Issue 1 is a duplicate of : https://github.com/ballerinalang/docerina/issues/142

**Comment by NatashaWso2** [comment]
This issue can be closed since issue 2 is fixed with #144 and issue 1 is a duplicate of #142
