### ISSUE TITLE
Cannot generate the docs if comments are added in the .bal file

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/docerina#66]
The following error is logged

`Docerina: API documentation generation failed for foo/bar/Structs3.bal: Structs3.bal:16:0: unwanted token '//struct Person {'`

**Comment by sameeragunarathne** [comment]
@dilinisg this is thrown at ballerina runtime when parsing a comment outside of the scope, for example comment outside a function,struct,connector scope etc. We only recommend to put doc comments using annotations for each compilation unit in ballerina.

**Comment by dilinisg** [comment]
This should be reported under ballerina run time. Hence closing the issue
