### ISSUE TITLE
Return parameter description is not set unless it is a named return type

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/docerina#68]
1. You have a unnamed return type as below.

@doc:Return(": Usage")
action getProjects(Redmine m, string text)(string ) {
                return text;

        }

2. Generate the docs

Issue
Description is not set for the return type

**Comment by nirmal070125** [comment]
@dilinisg can you try @doc:Return("Usage") and see? It should work.

**Comment by dilinisg** [comment]
Tried with @doc:Return("Result of execution") without the colon. The result is as shown in the screen shot

![screenshot from 2017-02-27 11-27-42](https://cloud.githubusercontent.com/assets/1845370/23350374/0f8193ca-fce0-11e6-8210-8753a10c0532.png)

**Comment by nirmal070125** [comment]
Yes, so it's okay right? @dilinisg ?

**Comment by dilinisg** [comment]
Yes, closing the issue
